spring:
  profiles:
    active: dev

  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
#    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 10
    min-idle: 1
    initial-size: 10
    tomcat:
      max-wait: 50000

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    suffix: .html
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    encoding: UTF-8
    servlet:
      content-type: text/html

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  messages:
    basename: BindingErrorMessages

application:
    perPageLimit: 10



